# GitHub Sponsors configuration
# Uncomment and configure if you want to enable sponsorship

# github: [yourusername]
# patreon: yourusername
# ko_fi: yourusername
# custom: ['https://your-website.com/donate']
